### ISSUE TITLE
parsing string to CF datetypes

### ISSUE THREAD

**Issue by kongdd** [JuliaGeo/CFTime.jl#15]
I need to parse "21001231" into `Date` with the calender type of `365_day` (`DateTimeNoLeap`).  
Any idea how to do that?

Thank u.

**Comment by Alexander-Barth** [comment]
This already work for me:

```julia
dt = DateTimeNoLeap("21001231",dateformat"yyyymmdd");
Dates.year(dt),Dates.month(dt),Dates.day(dt)
# output (2100, 12, 31)
```
(basically the same as julia's DateTime )

**Comment by kongdd** [comment]
Thank u.
