### ISSUE TITLE
Use default "days since 1900-01-01 00:00:00" as units kwarg for timeencode/decode?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/CFTime.jl#2]
It would be good to not have to specify this when automating conversions.

Edit: I may misunderstand exactly how this works... The end goal is to have reciprocal conversion to/from vectors of time types to strings without having to specify anything besides the DateTime objects so that NCDatasets can load and save vars of `AbstractCFDateTime` without and special casing. This is required for load/save to be easy and seemless in GeoData.jl.

**Comment by Balinus** [comment]
As far as I understand, I think this might lead to silent bug in user code. In principle the attribute "days since ..." or "seconds since ..." is part of the CF convention and it should always be present inside the netCDF file. So, I'm not sure there is a need for such a default.

**Comment by Alexander-Barth** [comment]
For timeencode / timedecode, the time origin and units is a mandatory positional argument. For NCDatasets, we define the units as `"days since 1900-01-01 00:00:00"` if the user forgets to set one. But I do not quite understand what is the issue with the current API in CFTime and NCDatasets.

**Comment by rafaqz** [comment]
I honestly can't remember what this was about, I think we mostly fixed conversion elsewhere.
