### ISSUE TITLE
Use types for calendar arg in timedecode and timencode, and allow types in timetype

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/CFTime.jl#3]
Requiring strings for the calendar type means the calling code has to convert the type to string if it want to encode the same calendar type. 

I think adding `timetype(dt::Type{<:AbstractCFDateTime}) = dt` would acheive this?

**Comment by Alexander-Barth** [comment]
Very nice, thanks! I added, `timetype(dt::Type{<:AbstractCFDateTime}) = dt`.
The following is now possible:

```julia
data = [0,1,2,3]
dt = CFTime.timedecode(DateTime360Day,data,"days since 2000-01-01 00:00:00")
data2 = CFTime.timeencode(dt,"days since 2000-01-01 00:00:00",DateTime360Day)
@test data == data2
```
