### ISSUE TITLE
Parsing delta_t to DatePeriod?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/CFTime.jl#8]
I would like to get time periods in julia `DatePeriod` object like `Month(1)` from netcdf time dimension `delta_t` fields like `"0000-01-00 00:00:00"`. This would give correct time ranges in GeoData.jl.

Are there tools here that would already do that, or get some of the way?

**Comment by rafaqz** [comment]
BTW I implemented this with something like:

```julia
function get_period(index, attrs)
    if haskey(attrs, "delta_t")
        period = parse_period(attrs["delta_t"])
    elseif haskey(attrs, "avg_period")
        period = parse_period(attrs["avg_period"])
    end
end

function parse_period(period_str::String)
    regex = r"(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)"
    mtch = match(regex, period_str)
    if mtch isa Nothing
        nothing
    else
        vals = Tuple(parse.(Int, mtch.captures))
        periods = (Year, Month, Day, Hour, Minute, Second)
        if length(vals) == length(periods)
            sum(map((p, v) -> p(v), periods, vals))
        end
    end
end
```

It could go here if you want.

**Comment by Alexander-Barth** [comment]
Is this part of the CF conventions? If yes, can you share a link that I can learn about it?
Thanks!

**Comment by rafaqz** [comment]
No sorry I released it's not CF, its CDC. It's just fairly common in netcdf files I use.

https://psl.noaa.gov/data/gridded/conventions/cdc_netcdf_standard.shtml

CF conventions don't seem to specify how to get the interval between time points, or at least I haven't been able to find anything clear. So to get the timespan in months you would have to use some heuristics to work out the closest interval to the points in the series, which is pretty awful, but guess I will have to write it at some stage. The difficult part is the spacing doesn't have to be equal so you need to check every date in the index to make sure it roughly e.g. month spaced for months in whatever the calendar is.

But when you know the step size in julia `DatePeriod` the index is a lot easier to work with - especially when the values are meant to be averages over the interval, and the point is just the middle of the month or 3hour period, etc.

**Comment by Alexander-Barth** [comment]
Thanks, but the aim for this package to just implement the CF conventions.
